doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetimemicrosecond: App\Doctrine\DBAL\Types\DateTimeMicrosecondType
        # lock_keys table is used by lock component, which is used by rate limiter
        schema_filter: ~^(?!lock_keys)~

    orm:
        auto_generate_proxy_classes: true
        dql:
            datetime_functions:
                Year: DoctrineExtensions\Query\Mysql\Year
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            -
                name: !php/const App\Doctrine\ORM\Filter\TrainingAreaPeriodFilter::FILTER_NAME
                class: App\Doctrine\ORM\Filter\TrainingAreaPeriodFilter
                enabled: false
