doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetimemicrosecond: App\Doctrine\DBAL\Types\DateTimeMicrosecondType

    orm:
        auto_generate_proxy_classes: true
        dql:
            datetime_functions:
                Year: DoctrineExtensions\Query\Mysql\Year
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
