# Service sub-domain mapping can be configured like so
# (Along with the relevant app.<service>.yaml file)
#
dispatch:
    - url: "admin.access-national-travel-survey.service.gov.uk/*"
      service: admin
