services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Ghost\GovUkFrontendBundle\Form\:
        resource: '../../Form/'

    Ghost\GovUkFrontendBundle\Twig\:
        resource: '../../Twig/'
